#!/bin/bash

if [ "$1" == "on" ]
then
	tvservice -p > /dev/null 2>&1
	sudo chvt 1 > /dev/null 2>&1
	sudo chvt 7 > /dev/null 2>&1
	echo "display_power=1"
elif [ "$1" == "off" ]
then
	tvservice -o > /dev/null 2>&1
	echo "display_power=0"
else
	RESULT=`tvservice -s 2>&1 | grep -c "off"`
	if [ $RESULT -lt 1 ]
	then
		echo "display_power=1"
	else
		echo "display_power=0"
	fi
fi
